### ISSUE TITLE
About time-steps

### ISSUE THREAD

**Issue by mingyueqingfeng2022** [diffusion-hyperfeatures/diffusion_hyperfeatures#9]

**Comment by g-luo** [comment]
Hi! Yes, we indeed aggregate at intervals of 5 (11 total steps as indicated in Table 1 of the paper, https://arxiv.org/abs/2305.14334). This is the maximum number of timesteps we aggregate from due to compute limitations, as we run our experiments on Nvidia Titan RTX GPUs, which have 24GiB of memory.

It's possible that aggregating even more timesteps could lead to better results, but this is an area of further research we did not investigate in the original paper.

**Comment by mingyueqingfeng2022** [comment]
Thanks for your patience in answering my question and I wish you more professional achievements on your research journey!
